### ISSUE TITLE
Invalid path due to colon

### ISSUE THREAD

**Issue by HappyReviewer** [researchart/fse20#139]
The colon character is invalid on Windows, this prevents checkout on the full report. Can you rename?

```
Resolving deltas: 100% (80417/80417), done.
error: invalid path 'submissions/available/Artifact for the ESECFSE 2020 Paper: An Empirical Analysis of the Costs of Clone- and Platform-Oriented Software Reuse/Accepted Paper.pdf'
```

https://github.com/researchart/fse20/tree/master/submissions/available/Artifact%20for%20the%20ESECFSE%202020%20Paper:%20An%20Empirical%20Analysis%20of%20the%20Costs%20of%20Clone-%20and%20Platform-Oriented%20Software%20Reuse

**Comment by kstolee** [comment]
@HappyReviewer Can you put this comment in the relevant issue?

**Comment by jacobkrueger** [comment]
I just renamed the folder in our repository, which comprised a colon. Working on Linux here, so I forgot that this was an issue. I also shortened the folder name a bit because some Windows systems are restricted in the file name lengths due to outdated libraries git has to use.

Regarding the comments of the reviewers, just as a side note, thanks for pointing out that one dataset was missing, we will add it. Unfortunately, we cannot release the full transcripts due to confidentiality, but the data in the files is what we got es explicit responses, and the quotations in the paper are representative of the general insights we obtained and were approved for publication.
